name: Validate Android

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/validate-android.yml'
      - 'packages/react-native-grpc/android/**'
      - '.editorconfig'
  pull_request:
    paths:
      - '.github/workflows/validate-android.yml'
      - 'packages/react-native-grpc/android/**'
      - '.editorconfig'

jobs:
  validate_android:
    name: Gradle Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.9

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17
          cache: gradle

      - name: Bootstrap
        run: |
          bun install
          bun nitro-codegen

      - name: Run Gradle Lint
        run: cd example/android && ./gradlew lint

      - name: Parse Gradle Lint Report
        uses: yutailang0119/action-android-lint@v4
        with:
          # ignore-warnings: true
          report-path: example/android/app/build/reports/*.xml
